export const listPartner = [
  {
    id: 1,
    accountId: "abc",
    status: 1,
    partnerFullName: "Lê Đăng Chiến",
    email: "dangchien@gmail.com",
    address: "Nguyên Xá, Minh Khai",
  },
  {
    id: 2,
    accountId: "abc",
    status: 2,
    partnerFullName: "Lê Đăng Chiến",
    email: "dangchien@gmail.com",
    address: "Nguyên Xá, Minh Khai",
  },
  {
    id: 3,
    accountId: "abc",
    status: 0,
    partnerFullName: "Lê Đăng Chiến",
    email: "dangchien@gmail.com",
    address: "Nguyên Xá, Minh Khai",
  },
  {
    id: 4,
    accountId: "abc",
    status: 1,
    partnerFullName: "Lê Đăng Chiến",
    email: "dangchien@gmail.com",
    address: "Nguyên Xá, Minh Khai",
  },
  {
    id: 5,
    accountId: "abc",
    status: 1,
    partnerFullName: "Lê Đăng Chiến",
    email: "dangchien@gmail.com",
    address: "Nguyên Xá, Minh Khai",
  },
];
