export const API_BASE_URL = 'http://localhost:8080/api/'

export const PARKING_SERVICE = {
  account: {
    createByAdmin: "parking/account/create-by-admin",
    searchListCustomer: "parking/account/search/customer",
    searchListPartner: "parking/account/search/partner",
    detailCustomer: "parking/account/customer/detail",
    detailPartner: "parking/account/partner/detail",
    getSuggestions: "parking/account/suggestions",
    getBalance: "parking/account/balance",
    infoAccount: "parking/account/info",
    changeStatus: "parking/account/change-status",
    changeInfo: "parking/account/change-info",
    changePassword: "parking/account/change-password",
    changeInfoPartner: "parking/account/change-info-partner",
  },
  location: {
    modify: "parking/location/modify",
    partnerSearch: "parking/location/partner/search",
    adminSearchWaitApprove: "parking/location/admin/search/wait-approve",
    adminSearch: "parking/location/admin/search",
    customerSearch: "parking/location/customer/search",
    approve: "parking/location/approve",
    modifyDetail: "parking/location/detail/modify",
    locationDetail: "parking/location/detail",
    customerDetail: "parking/location/customer/detail",
    waitReleaseDetail: "parking/location/detail/wait-release",
    getMapLocation: "parking/location/list/coordinates",
    getAllRecordIsActive: "parking/location/all/is-active",
    listDetail: "parking/location/list/detail",
    statisticsOfUsedPositions: "parking/location/statistics-of-used-positions",
    getSuggestions: "parking/location/suggestions",
  },
  ticket: {
    modify: "parking/ticket/modify",
    partnerSearch: "parking/ticket/partner/search",
    adminSearch: "parking/ticket/admin/search",
    customerSearch: "parking/ticket/search",
    detail: "parking/ticket/detail",
    customerTicketDetail: "parking/ticket/customer/detail",
    customerLocationUseTicket: "parking/ticket/customer/location-use-ticket",
    detailWaitRelease: "parking/ticket/detail/wait-release",
    partnerCancelRelease: "parking/ticket/partner/cancel/wait-release",
    adminCancelRelease: "parking/ticket/admin/cancel/wait-release",
    checkExistWaitRelease: "parking/ticket/check-exist-wait-release",
  },
  ticketPurchased: {
    customerSearch: "parking/purchased/customer/search",
    getQrCode: "parking/purchased/get-qr",
    refreshQr: "parking/purchased/new-qr",
    detail: "parking/purchased/detail",
    adminDetail: "parking/purchased/admin/detail",
    enableTicket: "parking/purchased/enable",
    disableTicket: "parking/purchased/disable",
    historyInOut: "parking/purchased/history/:id",
    historyInOutByAdmin: "parking/purchased/admin/history/:id",
    historyBuyTicket: "parking/purchased/history-buy-ticket",
    cancelTicket: "parking/purchased/cancel",
  },
  authen: {
    login: "parking/auth/sign-in",
    checkAccess: "parking/auth/check-token", 
    refreshToken: "parking/auth/refresh", 
    registration: "parking/auth/registration",
    confirmRegis: "parking/auth/confirm-regis",
    forget: "parking/auth/forget",
    confirmForget: "parking/auth/forget/confirm",
  },
  card: {
    customerAdditional: "parking/card/request/additional",
    customerCardApprove: "parking/card/approved",
    customerHistoryRequest: "parking/card/history/request",
    customerHistoryRequestOfCustomer: "parking/card/history/request-of",
    adminSearch: "parking/card/admin/search",
    adminSearchRequestAdd: "parking/card/admin/search/add",
    rejectRequest: "parking/card/reject-request",
    approveRequest: "parking/card/approve-request/:id",
    active: "parking/card/active",
    lock: "parking/card/lock/:id",
    permanentLock: "parking/card/permanent-lock/:id",
    linkTicket: "parking/card/link-ticket",
    unlinkTicket: "parking/card/cancel-link-ticket/:id",
    madeCard: "parking/card/made-card/:id",
    detailCardByadmin: "parking/card/admin/detail"
  },
  order: {
    createOrder: "parking/order",
    confirmOrder: "parking/order/confirm",
  },
  transaction: {
    customerSearch: "parking/transaction/history"
  },
  deposit: {
    requestDeposit: "parking/deposit",
    getHistory: "parking/deposit/history",
    cancelRequest: "parking/deposit/cancel/:id",
  },
  statistical: {
    getTicketOfCustomer: "parking/statistical/ticket-of-customer",
    getTransactionOfCustomer: "parking/statistical/transaction-of-customer",
    getTicketOfPartner: "parking/statistical/ticket-of-partner",
    StatisticalTicketWaitReleaseOfPartner: "parking/statistical/ticket-wait-approve-of-partner",
    getAllLocationOfPartner: "parking/location/list/coordinates-of-partner",
    getListTicketPurchaseOfPartner: "parking/statistical/ticket-purchased-of-partner",
    getLocationOfPartner: "parking/statistical/location-of-partner",
    getLocationWaitReleaseOfPartner: "parking/statistical/location-wait-release-of-partner",
    getLocationWaitApproveOfPartner: "parking/statistical/location-wait-approve-of-partner",
    getStatisticalCardAtHomeByAdmin: "parking/statistical/card-at-home-admin",
    getStatisticalPieAtHomeByAdmin: "parking/statistical/pie-at-home-admin",
    getStatisticalAreaAtHomeByAdmin: "parking/statistical/area-at-home-admin",
    thongKeDoanhThuThangTheoDoiTac: "parking/statistical/thong-ke-doanh-thu-thang-theo-doi-tac",
    statisticQuery: "parking/statistical/statistic-query",
  },
  checking: {
    historyByAdmin: "parking/checking/getByAccount",
    detail: "parking/checking/detail",
    listByTicket: "checking/getByTicket",
  }
}

export const NOTIFY_SERVICE = {
  notify: {
    countViewNotYet: "notify/count/viewed-not-yet",
    getAllNotify: "notify/get/all",
    viewedAll: "notify/view/all"
  }
}