server:
  port: 8081
spring:
  application:
    name: ParkingService
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: email, profile
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0                    # Không cần broker xác nhận
      retries: 0                 # Không retry
      properties:
        max.block.ms: 1000       # Tối đa chờ 1 giây khi thiếu metadata
        request.timeout.ms: 2000 # Timeout request tới broker
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
auth:
  token:
    time-live-access-token: 10000
    time-live-refresh-token: 10080
    secret-key: ${SECRET_KEY}
  check-user-agent: false
  forget:
    length-otp: 6
    time-quality: 5
    time-unit: m
crypto:
  AES:
    AES-SECRET_KEY: ${AES-SECRET_KEY:1234567890abcdef}

vnPay:
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  url-payment: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  secret-key: ${VNPAY-SECRET_KEY:DFI9X55CGVDGQFRX08ZRGSNJPEZZG4LL}
  tmnCode: ${VNPAY-VNP_TMN_CODE:7XG1D3QU}
DOMAIN_FE: ${DOMAIN_FE:http://localhost:3000}
logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
cloudinary:
  cloud_name: dis2ybh5i
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}