server:
  port: 8081
spring:
  application:
    name: ParkingService
  datasource:
    url: jdbc:mysql://localhost:3306/datn_parking
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: email, profile
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
auth:
  token:
    time-live-access-token: 5
    time-live-refresh-token: 10
    secret-key: ${SECRET_KEY}
  check-user-agent: false
  forget:
    length-otp: 6
    time-quality: 1
    time-unit: m