export const listNotify = [
  {
    id: 1,
    title: "Xin chào",
    content:
      "Nội dung thông báo Nội dung thông báo Nội dung thông báo Nội dung thông báo",
    link: "/account",
    createdAt: 1716345600,
    viewed: 0,
  },
  {
    id: 2,
    title: "Khuyến mãi đặc biệt",
    content: "Nhận ngay ưu đãi giảm giá lên đến 50% cho tất cả sản phẩm.",
    link: "/promotion",
    createdAt: 1716348600,
    viewed: 1,
  },
  {
    id: 3,
    title: "Cập nhật hệ thống",
    content: "Hệ thống sẽ bảo trì vào lúc 23:00 ngày 25/01/2025.",
    link: "/maintenance",
    createdAt: 1716351600,
    viewed: 0,
  },
  {
    id: 4,
    title: "Lời cảm ơn",
    content: "Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi trong năm qua.",
    link: "/thanks",
    createdAt: 1716354600,
    viewed: 1,
  },
  {
    id: 5,
    title: "Cập nhật bảo mật",
    content: "Hãy đổi mật khẩu định kỳ để đảm bảo an toàn tài khoản.",
    link: "/security",
    createdAt: 1716357600,
    viewed: 0,
  },
  {
    id: 6,
    title: "Thông báo lỗi",
    content: "Chúng tôi đang khắc phục sự cố đăng nhập, mong bạn thông cảm.",
    link: "/error",
    createdAt: 1716360600,
    viewed: 1,
  },
  {
    id: 7,
    title: "Chương trình khách hàng thân thiết",
    content: "Tích điểm đổi quà khi mua hàng trong tháng này.",
    link: "/loyalty",
    createdAt: 1716363600,
    viewed: 0,
  },
  {
    id: 8,
    title: "Thông báo tuyển dụng",
    content: "Công ty đang mở đợt tuyển dụng mới cho nhiều vị trí.",
    link: "/careers",
    createdAt: 1716366600,
    viewed: 0,
  },
  {
    id: 9,
    title: "Cập nhật tính năng mới",
    content: "Khám phá những tính năng mới của chúng tôi ngay hôm nay.",
    link: "/features",
    createdAt: 1716369600,
    viewed: 1,
  },
  {
    id: 10,
    title: "Hướng dẫn sử dụng",
    content: "Xem hướng dẫn sử dụng chi tiết tại trang hỗ trợ.",
    link: "/help",
    createdAt: 1716372600,
    viewed: 0,
  },
];
