server:
  port: 8082
spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:mysql://localhost:3306/datn_parking
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
